In [32]:
import pandas as pd
import numpy as np
from textblob import TextBlob

In [20]:
cust_df = pd.read_csv("customers.csv")

In [21]:
cust_df.head()

  marketplace  customer_id vine
0          US     32158956    N
1          US      2714559    N
2          US     12608825    N
3          US     25482800    N
4          US      9310286    N

In [22]:
prod_df = pd.read_csv("products.csv")

In [23]:
prod_df.head()

,product_id,product_parent,product_title,product_category
0,B01KL6O72Y,24485154,Easy Tool Stainless Steel Fruit Pineapple Core...,Apparel
1,B01ID3ZS5W,363128556,V28 Women Cowl Neck Knit Stretchable Elasticit...,Apparel
2,B01I497BGY,811958549,James Fiallo Men's 12-Pairs Low Cut Athletic S...,Apparel
3,B01HDXFZK6,692205728,Belfry Gangster 100% Wool Stain-Resistant Crus...,Apparel
4,B01G6MBEBY,431150422,JAEDEN Women's Beaded Spaghetti Straps Sexy Lo...,Apparel

In [24]:
revi_df = pd.read_csv("reviews.csv")

In [25]:
revi_df.head()

,marketplace,customer_id,review_id,product_id,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date
0,US,32158956,R1KKOXHNI8MSXU,B01KL6O72Y,4,0,0,N,Y,★ THESE REALLY DO WORK GREAT WITH SOME TWEAKING ★,"These Really Do Work Great, But You Do Need To...",14-01-2013
1,US,2714559,R26SP2OPDK4HT7,B01ID3ZS5W,5,1,2,N,Y,Favorite for winter. Very warm!,I love this dress. Absolute favorite for winte...,04-03-2014
2,US,12608825,RWQEDYAX373I1,B01I497BGY,5,0,0,N,Y,Great Socks for the money.,"Nice socks, great colors, just enough support ...",12-07-2015
3,US,25482800,R231YI7R4GPF6J,B01HDXFZK6,5,0,0,N,Y,Slick hat!,"I bought this for my husband and WOW, this is ...",03-06-2015
4,US,9310286,R3KO3W45DD0L1K,B01G6MBEBY,5,0,0,N,Y,I would do it again!,Perfect dress and the customer service was awe...,12-06-2015

In [26]:
revi_df.isnull().sum()

marketplace            0
customer_id            0
review_id              0
product_id             0
star_rating            0
helpful_votes          0
total_votes            0
vine                   0
verified_purchase      0
review_headline       73
review_body          121
review_date            0
dtype: int64

In [27]:
revi_df.dropna(inplace=True)

In [28]:
revi_df.head()

,marketplace,customer_id,review_id,product_id,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date
0,US,32158956,R1KKOXHNI8MSXU,B01KL6O72Y,4,0,0,N,Y,★ THESE REALLY DO WORK GREAT WITH SOME TWEAKING ★,"These Really Do Work Great, But You Do Need To...",14-01-2013
1,US,2714559,R26SP2OPDK4HT7,B01ID3ZS5W,5,1,2,N,Y,Favorite for winter. Very warm!,I love this dress. Absolute favorite for winte...,04-03-2014
2,US,12608825,RWQEDYAX373I1,B01I497BGY,5,0,0,N,Y,Great Socks for the money.,"Nice socks, great colors, just enough support ...",12-07-2015
3,US,25482800,R231YI7R4GPF6J,B01HDXFZK6,5,0,0,N,Y,Slick hat!,"I bought this for my husband and WOW, this is ...",03-06-2015
4,US,9310286,R3KO3W45DD0L1K,B01G6MBEBY,5,0,0,N,Y,I would do it again!,Perfect dress and the customer service was awe...,12-06-2015

In [31]:
revi_df.isnull().sum()

marketplace          0
customer_id          0
review_id            0
product_id           0
star_rating          0
helpful_votes        0
total_votes          0
vine                 0
verified_purchase    0
review_headline      0
review_body          0
review_date          0
dtype: int64

In [29]:
cust_df.isnull().sum()

marketplace    0
customer_id    0
vine           0
dtype: int64

In [30]:
prod_df.isnull().sum()

product_id          0
product_parent      0
product_title       0
product_category    0
dtype: int64

In [33]:
# Function to get sentiment
def get_sentiment(text):
    blob = TextBlob(str(text))  # ensure it's a string
    polarity = blob.sentiment.polarity
    if polarity > 0:
        return 'positive'
    elif polarity < 0:
        return 'negative'
    else:
        return 'neutral'

In [35]:
# Apply the function to create a new column
revi_df['sentiment'] = revi_df['review_body'].apply(get_sentiment)

In [36]:
revi_df.head()

,marketplace,customer_id,review_id,product_id,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date,sentiment
0,US,32158956,R1KKOXHNI8MSXU,B01KL6O72Y,4,0,0,N,Y,★ THESE REALLY DO WORK GREAT WITH SOME TWEAKING ★,"These Really Do Work Great, But You Do Need To...",14-01-2013,positive
1,US,2714559,R26SP2OPDK4HT7,B01ID3ZS5W,5,1,2,N,Y,Favorite for winter. Very warm!,I love this dress. Absolute favorite for winte...,04-03-2014,positive
2,US,12608825,RWQEDYAX373I1,B01I497BGY,5,0,0,N,Y,Great Socks for the money.,"Nice socks, great colors, just enough support ...",12-07-2015,positive
3,US,25482800,R231YI7R4GPF6J,B01HDXFZK6,5,0,0,N,Y,Slick hat!,"I bought this for my husband and WOW, this is ...",03-06-2015,positive
4,US,9310286,R3KO3W45DD0L1K,B01G6MBEBY,5,0,0,N,Y,I would do it again!,Perfect dress and the customer service was awe...,12-06-2015,positive

In [39]:
revi_df[revi_df['sentiment'] == 'neutral']

,marketplace,customer_id,review_id,product_id,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date,sentiment
15,US,27097189,R1OJA3DJL0VDDK,B019438FEG,5,0,0,N,Y,Five Stars,I have this Columbia in 5 colors and wear them...,20-10-2014,neutral
16,US,13808904,R1THWA5YRJLOOF,B0178HGNIA,4,0,0,N,Y,Four Stars,My husband found these so comfy that this is o...,05-07-2015,neutral
44,US,17276940,RAMFU8B8PE62H,B014G24NS2,1,0,0,N,N,WRONG PLACE,ITS THE PUERTO RICAN FLAG.,27-08-2015,neutral
55,US,2476688,R118S1ZIB2M80R,B014DJM1HI,5,0,0,N,N,Cute Henley shirt,"I purchased this in Winter White, and I like i...",25-08-2015,neutral
59,US,22759539,R29NCKCU420Z13,B014CRV0R8,1,0,0,N,N,One Star,Eastern Washington University's mascot is the ...,24-08-2015,neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...
306879,US,1061333,RO5WOL4LWMKDL,B004KX3262,1,0,0,N,Y,One Star,It came without the chain,14-08-2015,neutral
306880,US,186650,R248ER2L2C7LJT,B00564MDEG,4,0,0,N,Y,"It just arrived in the mail yesterday, so far ...",The crown might have some issues.,14-08-2015,neutral
306902,US,269074,R2VH1WY571NO8U,B008BWM6SS,1,0,0,N,Y,One Star,Broke almost immediately,14-08-2015,neutral
306913,US,44272709,R3ML2P0ZBTWG6U,B005FN0WRI,5,0,0,N,Y,Five Stars,Excelent,14-08-2015,neutral
306930,US,49678384,R26AQN918M55SG,B00WNB3UY2,2,0,0,N,Y,Two Stars,It's to fragile,14-08-2015,neutral

In [40]:
merged_df = pd.merge(revi_df, prod_df, on='product_id')

In [41]:
merged_df.head()

,marketplace,customer_id,review_id,product_id,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date,sentiment,product_parent,product_title,product_category
0,US,32158956,R1KKOXHNI8MSXU,B01KL6O72Y,4,0,0,N,Y,★ THESE REALLY DO WORK GREAT WITH SOME TWEAKING ★,"These Really Do Work Great, But You Do Need To...",14-01-2013,positive,24485154,Easy Tool Stainless Steel Fruit Pineapple Core...,Apparel
1,US,2714559,R26SP2OPDK4HT7,B01ID3ZS5W,5,1,2,N,Y,Favorite for winter. Very warm!,I love this dress. Absolute favorite for winte...,04-03-2014,positive,363128556,V28 Women Cowl Neck Knit Stretchable Elasticit...,Apparel
2,US,12608825,RWQEDYAX373I1,B01I497BGY,5,0,0,N,Y,Great Socks for the money.,"Nice socks, great colors, just enough support ...",12-07-2015,positive,811958549,James Fiallo Men's 12-Pairs Low Cut Athletic S...,Apparel
3,US,25482800,R231YI7R4GPF6J,B01HDXFZK6,5,0,0,N,Y,Slick hat!,"I bought this for my husband and WOW, this is ...",03-06-2015,positive,692205728,Belfry Gangster 100% Wool Stain-Resistant Crus...,Apparel
4,US,9310286,R3KO3W45DD0L1K,B01G6MBEBY,5,0,0,N,Y,I would do it again!,Perfect dress and the customer service was awe...,12-06-2015,positive,431150422,JAEDEN Women's Beaded Spaghetti Straps Sexy Lo...,Apparel

In [42]:
merged_df.isnull().sum()

marketplace          0
customer_id          0
review_id            0
product_id           0
star_rating          0
helpful_votes        0
total_votes          0
vine                 0
verified_purchase    0
review_headline      0
review_body          0
review_date          0
sentiment            0
product_parent       0
product_title        0
product_category     0
dtype: int64

In [43]:
merged_df = merged_df[[
    'marketplace',
    'customer_id',
    'review_id',
    'product_id',
    'product_parent',
    'product_title',
    'product_category',
    'star_rating',
    'helpful_votes',
    'total_votes',
    'vine',
    'verified_purchase',
    'review_headline',
    'review_body',
    'review_date',
    'sentiment' 
]]

In [44]:
merged_df.isnull().sum()

marketplace          0
customer_id          0
review_id            0
product_id           0
product_parent       0
product_title        0
product_category     0
star_rating          0
helpful_votes        0
total_votes          0
vine                 0
verified_purchase    0
review_headline      0
review_body          0
review_date          0
sentiment            0
dtype: int64

In [45]:
merged_df

,marketplace,customer_id,review_id,product_id,product_parent,product_title,product_category,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date,sentiment
0,US,32158956,R1KKOXHNI8MSXU,B01KL6O72Y,24485154,Easy Tool Stainless Steel Fruit Pineapple Core...,Apparel,4,0,0,N,Y,★ THESE REALLY DO WORK GREAT WITH SOME TWEAKING ★,"These Really Do Work Great, But You Do Need To...",14-01-2013,positive
1,US,2714559,R26SP2OPDK4HT7,B01ID3ZS5W,363128556,V28 Women Cowl Neck Knit Stretchable Elasticit...,Apparel,5,1,2,N,Y,Favorite for winter. Very warm!,I love this dress. Absolute favorite for winte...,04-03-2014,positive
2,US,12608825,RWQEDYAX373I1,B01I497BGY,811958549,James Fiallo Men's 12-Pairs Low Cut Athletic S...,Apparel,5,0,0,N,Y,Great Socks for the money.,"Nice socks, great colors, just enough support ...",12-07-2015,positive
3,US,25482800,R231YI7R4GPF6J,B01HDXFZK6,692205728,Belfry Gangster 100% Wool Stain-Resistant Crus...,Apparel,5,0,0,N,Y,Slick hat!,"I bought this for my husband and WOW, this is ...",03-06-2015,positive
4,US,9310286,R3KO3W45DD0L1K,B01G6MBEBY,431150422,JAEDEN Women's Beaded Spaghetti Straps Sexy Lo...,Apparel,5,0,0,N,Y,I would do it again!,Perfect dress and the customer service was awe...,12-06-2015,positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306765,US,10778771,R12ILN37YTU0HB,B004WFWLCY,714030469,Android Women's AD512AWGY Exotic White Ceramic...,Watches,5,0,0,N,Y,it looks better in,This watch is rated 5...it looks better in person,14-08-2015,positive
306766,US,31986889,R1Z1WT0IMSLWVA,B002PAPT1S,246117564,Invicta Men's 6620 II Collection Chronograph S...,Watches,5,0,0,N,Y,"Very Nice, they need to make adjustments to band","Very Nice,they need to make adjustments to ban...",14-08-2015,positive
306767,US,40384923,R2O3H1NUCGRO05,B00NYLBU1A,752179957,Nixon A105-1959 Mens The Sentry Leather Dark C...,Watches,4,0,0,N,Y,Four Stars,Nice looking watch band is sporty and color co...,14-08-2015,positive
306768,US,49959991,RHYLWMZCFBDDL,B009MA9GPE,200509702,PromiseU Leather Bracelet Woman Rhinestone Riv...,Watches,5,0,0,N,Y,"Item arrived on time, goes with everything ver...","Item arrived on time,goes with everything very...",14-08-2015,positive
306769,US,9882621,R4M9D8VU6VYQV,B000SZKHPA,190544499,Timex Women's T5G881 1440 Digital Watch with W...,Watches,5,0,0,N,Y,Five Stars,Great watch for the price!,14-08-2015,positive

In [46]:
merged_df.to_csv('amazon_reviews.csv', index=False)